
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label Num1;
	private global::Gtk.Entry entry3;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label Num2;
	private global::Gtk.Entry entry1;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label result;
	private global::Gtk.Entry Resultado;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Button Sum;
	private global::Gtk.Button Reset;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Num1 = new global::Gtk.Label ();
		this.Num1.Name = "Num1";
		this.Num1.LabelProp = global::Mono.Unix.Catalog.GetString ("Num1");
		this.hbox5.Add (this.Num1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.Num1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '•';
		this.hbox5.Add (this.entry3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entry3]));
		w2.Position = 1;
		this.vbox3.Add (this.hbox5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.Num2 = new global::Gtk.Label ();
		this.Num2.Name = "Num2";
		this.Num2.LabelProp = global::Mono.Unix.Catalog.GetString ("Num2");
		this.hbox6.Add (this.Num2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.Num2]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.hbox6.Add (this.entry1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entry1]));
		w5.Position = 1;
		this.vbox4.Add (this.hbox6);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox6]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.result = new global::Gtk.Label ();
		this.result.Name = "result";
		this.result.LabelProp = global::Mono.Unix.Catalog.GetString ("result");
		this.hbox7.Add (this.result);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.result]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.Resultado = new global::Gtk.Entry ();
		this.Resultado.CanFocus = true;
		this.Resultado.Name = "Resultado";
		this.Resultado.IsEditable = true;
		this.Resultado.InvisibleChar = '•';
		this.hbox7.Add (this.Resultado);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.Resultado]));
		w8.Position = 1;
		this.vbox4.Add (this.hbox7);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox7]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.Sum = new global::Gtk.Button ();
		this.Sum.CanFocus = true;
		this.Sum.Name = "Sum";
		this.Sum.UseUnderline = true;
		this.Sum.Label = global::Mono.Unix.Catalog.GetString ("Sum");
		this.hbox8.Add (this.Sum);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.Sum]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.Reset = new global::Gtk.Button ();
		this.Reset.CanFocus = true;
		this.Reset.Name = "Reset";
		this.Reset.UseUnderline = true;
		this.Reset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.hbox8.Add (this.Reset);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.Reset]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox4.Add (this.hbox8);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox8]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox3.Add (this.vbox4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Sum.Clicked += new global::System.EventHandler (this.OnSumClicked);
		this.Reset.Clicked += new global::System.EventHandler (this.OnResetClicked);
	}
}
